language: node_js
sudo: true
node_js:
  - '8.9.0'
install: 
  - 'npm install -g gulp-cli'
  - 'npm install -g lerna'
  - 'cd packages;'
  - 'npm install;'
  - 'files=(*)'
  - 'for item in ${files[*]}'
  - 'do'
  - '  if [ -d $item ]; then'
  - '    cd $item;'
  - '    cp -R ../../node_modules ./'
  - '    npm install;'
  - '    gulp build;'
  - '    cd ..;'
  - '  fi'
  - 'done'
  - 'lerna bootstrap;'
script:
  - 'cd packages;'
  - 'files=(*)'
  - 'for item in ${files[*]}'
  - 'do'
  - '  if [ -d $item ]; then'
  - '    cd $item;'
  - '    cp -R ../../node_modules ./'
  - '    gulp build;'
  - '    cd ..;'
  - '  fi'
  - 'done'
