language: node_js
node_js:
  - '8.9.0'
before_install: 
    - 'npm install -g gulp-cli'
    - 'sudo npm install -g lerna'
install:
    - 'sudo ./scripts/init.sh'
script:
    - 'sudo ./scripts/build.sh'